version: 2
jobs:
  build:
    working_directory: /go/src/capsulecd
    docker:
      - image: docker:17.06.1-ce-git
        environment:
          GOROOT: /usr/lib/go
          GOPATH: /go
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Install dependencies
          command: |
            env
            docker info
            apk --update-cache --allow-untrusted \
                add go build-base bash curl \
                && rm -rf /var/cache/apk/*

            mkdir -p /coverage

            # Configure Go
            mkdir -p ${GOPATH}/src ${GOPATH}/bin

            docker pull analogj/libgit2-crossbuild:linux-amd64
# Use docker image caching if this is slow.
# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
      - run:
          name: Build application Docker image
          command: |
            docker build -f ci/Dockerfile.base --tag analogj/capsulecd-build:base .
            docker build -f ci/Dockerfile.chef --tag analogj/capsulecd-build:chef .
            docker build -f ci/Dockerfile.node --tag analogj/capsulecd-build:node .
            docker build -f ci/Dockerfile.python --tag analogj/capsulecd-build:python .
            docker build -f ci/Dockerfile.ruby --tag analogj/capsulecd-build:ruby .
            docker build -f ci/Dockerfile.golang --tag analogj/capsulecd-build:golang .
      - run:
          name: Run Base Docker containers with coverage
          shell: bash
          command: |
            CAPSULECD_ENV=base
            echo "#################################################### $CAPSULECD_ENV"
            docker run -e "CI=true" \
              --name $CAPSULECD_ENV \
              analogj/capsulecd-build:$CAPSULECD_ENV \
              ./ci/coverage.sh $CAPSULECD_ENV

            echo "exit code $?"

            docker cp $CAPSULECD_ENV:/coverage/coverage-$CAPSULECD_ENV.txt /coverage
      - run:
          name: Run Chef Docker containers with coverage
          shell: bash
          command: |
            CAPSULECD_ENV=chef
            echo "#################################################### $CAPSULECD_ENV"
            docker run -e "CI=true" \
              --name $CAPSULECD_ENV \
              analogj/capsulecd-build:$CAPSULECD_ENV \
              ./ci/coverage.sh $CAPSULECD_ENV

            echo "exit code $?"

            docker cp $CAPSULECD_ENV:/coverage/coverage-$CAPSULECD_ENV.txt /coverage
      - run:
          name: Run Node Docker containers with coverage
          shell: bash
          command: |
            CAPSULECD_ENV=node
            echo "#################################################### $CAPSULECD_ENV"
            docker run -e "CI=true" \
              --name $CAPSULECD_ENV \
              analogj/capsulecd-build:$CAPSULECD_ENV \
              ./ci/coverage.sh $CAPSULECD_ENV

            echo "exit code $?"
            docker cp $CAPSULECD_ENV:/coverage/coverage-$CAPSULECD_ENV.txt /coverage
      - run:
          name: Run Python Docker containers with coverage
          shell: bash
          command: |
            CAPSULECD_ENV=python
            echo "#################################################### $CAPSULECD_ENV"
            docker run -e "CI=true" \
              --name $CAPSULECD_ENV \
              analogj/capsulecd-build:$CAPSULECD_ENV \
              ./ci/coverage.sh $CAPSULECD_ENV
            echo "exit code $?"
            docker cp $CAPSULECD_ENV:/coverage/coverage-$CAPSULECD_ENV.txt /coverage
      - run:
          name: Run Ruby Docker containers with coverage
          shell: bash
          command: |
            CAPSULECD_ENV=ruby
            echo "#################################################### $CAPSULECD_ENV"
            docker run -e "CI=true" \
              --name $CAPSULECD_ENV \
              analogj/capsulecd-build:$CAPSULECD_ENV \
              ./ci/coverage.sh $CAPSULECD_ENV
            echo "exit code $?"
            docker cp $CAPSULECD_ENV:/coverage/coverage-$CAPSULECD_ENV.txt /coverage
      - run:
          name: Run Golang Docker containers with coverage
          shell: bash
          command: |
            CAPSULECD_ENV=golang
            echo "#################################################### $CAPSULECD_ENV"
            docker run -e "CI=true" \
              --name $CAPSULECD_ENV \
              analogj/capsulecd-build:$CAPSULECD_ENV \
              ./ci/coverage.sh $CAPSULECD_ENV
            echo "exit code $?"
            docker cp $CAPSULECD_ENV:/coverage/coverage-$CAPSULECD_ENV.txt /coverage

      - run:
          name: Merge coverage reports and submit
          shell: bash
          command: |
            ls -alt /coverage

            # upload to codecov.
            bash <(curl -s https://codecov.io/bash) -f "*.txt" -s /coverage
            echo "exit code $?"
#      - run:
#          name: Merge generated coverage reports using webhook.
#          command: |



#
