version: 2
jobs:
  build:
    working_directory: /go/src/capsulecd
    docker:
      - image: docker:17.06.1-ce-git
        environment:
          GOROOT: /usr/lib/go
          GOPATH: /go
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Install dependencies
          command: |
            env
            docker info
            apk --update-cache --allow-untrusted \
                add go build-base bash curl \
                && rm -rf /var/cache/apk/*

            # Configure Go
            mkdir -p ${GOPATH}/src ${GOPATH}/bin

            docker pull analogj/libgit2-crossbuild:linux-amd64
# Use docker image caching if this is slow.
# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
      - run:
          name: Build application Docker image
          command: |
            docker build -f ci/Dockerfile.base --tag analogj/capsulecd-build:base .
            docker build -f ci/Dockerfile.chef --tag analogj/capsulecd-build:chef .
#           docker build -f ci/Dockerfile.golang --tag analogj/capsulecd-build:golang .
#           docker build -f ci/Dockerfile.node --tag analogj/capsulecd-build:node .
#           docker build -f ci/Dockerfile.python --tag analogj/capsulecd-build:python .
#           docker build -f ci/Dockerfile.ruby --tag analogj/capsulecd-build:ruby .
      - run:
          name: Run Docker containers with coverage
          shell: bash
          command: |
            mkdir -p /coverage

            echo "#################################################### BASE"
            docker run -e "CI=true" \
              -v /coverage:/coverage \
              analogj/capsulecd-build:base \
              ./ci/coverage.sh base

            echo "#################################################### CHEF"
            docker run -e "CI=true" \
              -v /coverage:/coverage \
              analogj/capsulecd-build:chef \
              ./ci/coverage.sh chef

            ls -alt /coverage

            # upload to codecov.
            bash <(curl -s https://codecov.io/bash) -f "/coverage/*.txt"

#          docker run -e "CI=true" -v /coverage:/tmp/coverage analogj/capsulecd-build:golang
#          docker run -e "CI=true" -v /coverage:/tmp/coverage analogj/capsulecd-build:node
#          docker run -e "CI=true" -v /coverage:/tmp/coverage analogj/capsulecd-build:python
#          docker run -e "CI=true" -v /coverage:/tmp/coverage analogj/capsulecd-build:ruby

#      - run:
#          name: Merge generated coverage reports using webhook.
#          command: |



#
