from spheromak/docker-chefdk
maintainer Jason Kulatunga <jk17@ualberta.ca>

# Make Chef DK the primary Ruby/Chef development environment.
run echo 'eval "$(chef shell-init bash)"' >> ~/.bash_profile
run echo 'eval "$(chef shell-init bash)"' >> ~/.bashrc

run gem install bundler

# copy the application files to the image
workdir /srv/capsulecd
copy . /srv/capsulecd/
run bundle install --without node ruby